<a href="https://colab.research.google.com/github/SAIFIANS/DS_L/blob/main/DS_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Python, Be good with me")

Python, Be good with me


In [2]:
# COMMENT
# ENTER WILL ADD A LINE WITHOUT RUNNING THE CODE
# CTRL ENTER WILL RUN THE LINE
# ALT ENTER WILL RUN THE LINE & ADD A NEW LINE
# SHIFT ENTER WILL RUN THE CODE & MOVE TO THE NEXT LINE

In [3]:
# [] - list, data extraction & slicing
# {} - dictionary
# () - set

In [4]:
import math

In [5]:
math.sqrt(64)

8.0

In [6]:
import numpy as np
from numpy.random import randn

In [7]:
x = randn()
x

-1.2077282313452729

In [8]:
result = None
x = randn()
if x >1:
  result = 'greater than 1'
print(x)
print(result)

0.4882166175352098
None


In [9]:
reult = None
x = randn()
if x>1:
  result = 'Greater than 1'
else:
  result = 'Less than 1'
print(x)
print(result)

-0.6100569960333261
Less than 1


In [10]:
reult = None
x = randn()
if x>1:
  result = 'Greater than 1'
elif x>=-1:
  result = 'Between -1 and 1'
else:
  result = 'Less than 1'
print(x)
print(result)


-0.20878939103700653
Between -1 and 1


In [11]:
list2 = ['Saifi',20,40.5,True]

In [12]:
list2[1]=100

In [13]:
list2

['Saifi', 100, 40.5, True]

In [14]:
type(list2[3])

bool

In [15]:
letters = ['A','B','C','D','E','F','G','H','I','J']

In [16]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [17]:
letters[1:6:-1]

[]

In [18]:
letters[6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [19]:
tuple1 = (56, 78,'Bradly')

In [21]:
tuple1[1]

78

In [22]:
tuple1[1]= 80 #tuple is immutable

TypeError: ignored

In [25]:
list(letters)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [28]:
type(tuple1)

tuple

In [29]:
print(tuple1)

(56, 78, 'Bradly')


In [31]:
len(tuple1)

3

In [32]:
list1 = [47,35,88.6]

In [35]:
max(list1)

88.6

In [39]:
list3 = [1,'Brad',30.6,True]

In [41]:
a =np.array(list3)

In [42]:
a

array(['1', 'Brad', '30.6', 'True'], dtype='<U32')

In [44]:
list4 = [1,30.6,True]
b = np.array(list4)
b

array([ 1. , 30.6,  1. ])

In [45]:
list5 = [1,False]
c=np.array(list5)
c

array([1, 0])

In [46]:
list6 =[False]
d=np.array(list6)
d

array([False])

In [47]:
# Hierarchy of datatypes - String > Float > Integer > Boolean

In [49]:
list3
a =np.array(list3)
a

array(['1', 'Brad', '30.6', 'True'], dtype='<U32')

In [50]:
a[1]

'Brad'

In [51]:
a[1:3]

array(['Brad', '30.6'], dtype='<U32')

In [52]:
a[1:]

array(['Brad', '30.6', 'True'], dtype='<U32')

In [53]:
a[:-1]

array(['1', 'Brad', '30.6'], dtype='<U32')

{'Sat', 'Wen', 'Sun', 'Fri', 'Thu', 'Mon', 'Tue'}


In [60]:
# Removing list elements from a set using a loop
a= ["Tue","Wed","Thu"]
b={"Fri","Sat","Thu","Mon","Tue","Wed","Sun"}
for i in a:
  if (i!=a):
    b.remove(i)
print(b)

{'Mon', 'Sat', 'Sun', 'Fri'}


In [61]:
DaysA = set(["Mon","Tue","Wen","Thu","Sat"])
DaysB = set(["Wen","Thu","Fri","Sat","Sun"])
AllDays = DaysA|DaysB
print(AllDays)

{'Sat', 'Wen', 'Sun', 'Fri', 'Thu', 'Mon', 'Tue'}


In [62]:
print(DaysA.union(DaysB))
print(DaysB.union(DaysA))

{'Sat', 'Wen', 'Sun', 'Fri', 'Thu', 'Mon', 'Tue'}
{'Sat', 'Wen', 'Sun', 'Fri', 'Thu', 'Mon', 'Tue'}


In [63]:
# Union of Three Sets
'''Elements either in A, B or C, or all 3 or any 2 of the sets.
will be taken in union'''
A={1,2,6,5,7}
B={8,7,1,5}
C={10,14,15}
A|B|C

{1, 2, 5, 6, 7, 8, 10, 14, 15}

In [64]:
A.union(B,C)

{1, 2, 5, 6, 7, 8, 10, 14, 15}

In [65]:
B.union(A,C)

{1, 2, 5, 6, 7, 8, 10, 14, 15}

In [66]:
C.union(B,A)

{1, 2, 5, 6, 7, 8, 10, 14, 15}

In [68]:
DaysA = set(["Mon","Tue","Wed","Sat"])
DaysB = set(["Wed","Thu","Sat","Sun"])
AllDays = DaysA & DaysB
print(AllDays)

{'Sat', 'Wed'}


In [69]:
print(DaysA.intersection(DaysB))
print(DaysB.intersection(DaysA))

{'Sat', 'Wed'}
{'Sat', 'Wed'}


In [ ]:
# stats.iloc[:1,3:].values
# 2nd the 5th row, column 1 and 3
# stats.iloc[2:6:3,1:4:2].values

